<?php
namespace App\Models\Detail\BgImb;

use App\Enum\Status;

class BgImbTransformer{

    public function transformDetail($model) {
        return [
            'id' => $model->id,
            'lokasi_kode' => $model->lokasi_kode,
            'thn_periode_keg' => $model->thn_periode_keg,
            'nama_propinsi' => $model->nama_propinsi,
            'nama_kabupatenkota' => $model->nama_kabupatenkota,
            'propinsi_id' => !empty($model->lokasi) ? $model->lokasi->lokasi_propinsi : null,
            'kota_id' => !empty($model->lokasi) ? $model->lokasi->lokasi_kabupatenkota : null,
            'no_perbub_perwal' => $model->no_perbub_perwal,
'tgl_penetapan_perbub_perwal' => $model->tgl_penetapan_perbub_perwal,
'file_upload_perbub_perwal' => $model->file_upload_perbub_perwal,
'no_surat_krk' => $model->no_surat_krk,
'nama_permohonan_imb' => $model->nama_permohonan_imb,
'nama_pemilik_perorangan_bg_imb' => $model->nama_pemilik_perorangan_bg_imb,
'pemilik_perorangan_bg_imb_id' => $model->pemilik_perorangan_bg_imb_id,
'nama_pemilik_badan_usaha_bg_imb' => $model->nama_pemilik_badan_usaha_bg_imb,
'no_akta_pendirian_badan_usaha_bg_imb' => $model->no_akta_pendirian_badan_usaha_bg_imb,
'nama_institusi_imb' => $model->nama_institusi_imb,
'no_ikmn_pemerintah_imb' => $model->no_ikmn_pemerintah_imb,
'no_hdno_pemerintah_imb' => $model->no_hdno_pemerintah_imb,
'propinsi_pemilik_bg_imb' => $model->propinsi_pemilik_bg_imb,
'kabkota_pemilik_bg_imb' => $model->kabkota_pemilik_bg_imb,
'kec_pemilik_bg_imb' => $model->kec_pemilik_bg_imb,
'kel_pemilik_bg_imb' => $model->kel_pemilik_bg_imb,
'rt_pemilik_bg_imb' => $model->rt_pemilik_bg_imb,
'rw_pemilik_bg_imb' => $model->rw_pemilik_bg_imb,
'alamat_pemilik_bg_imb' => $model->alamat_pemilik_bg_imb,
'telp_pemilik_bg_imb' => $model->telp_pemilik_bg_imb,
'email_pemilik_bg_imb' => $model->email_pemilik_bg_imb,
'nama_pemilik_tanah' => $model->nama_pemilik_tanah,
'no_bukti_kepemilikan' => $model->no_bukti_kepemilikan,
'jenis_bukti_kepemilikan' => $model->jenis_bukti_kepemilikan,
'luas_tanah' => $model->luas_tanah,
'satuan_luas_tanah' => $model->satuan_luas_tanah,
'fungsi_bg' => $model->fungsi_bg,
'jml_lantai_bg' => $model->jml_lantai_bg,
'luas_bg' => $model->luas_bg,
'satuan_luas_bg' => $model->satuan_luas_bg,
'luas_lantai_basement' => $model->luas_lantai_basement,
'satuan_lantai_basement' => $model->satuan_lantai_basement,
'tgl_mulai_konstruksi' => $model->tgl_mulai_konstruksi,
'tgl_selesai_konstruksi' => $model->tgl_selesai_konstruksi,
'nilai_bg_sesuai_rab' => $model->nilai_bg_sesuai_rab,
'lat_bg' => $model->lat_bg,
'long_bg' => $model->long_bg,
'tek_bg_rg_terbuka_hijau_pekarangan' => $model->tek_bg_rg_terbuka_hijau_pekarangan,
'tek_bg_limbah_b3' => $model->tek_bg_limbah_b3,
'tek_bg_memiliki_perangkat_penangkal_kebakaran' => $model->tek_bg_memiliki_perangkat_penangkal_kebakaran,
'tek_jenis_sanitasi' => $model->tek_jenis_sanitasi,
'tek_bg_sumber_air' => $model->tek_bg_sumber_air,
'penyedia_js_perencanaan_arsitektur' => $model->penyedia_js_perencanaan_arsitektur,
'no_serti_js_perencanaan_arsitektur' => $model->no_serti_js_perencanaan_arsitektur,
'penyedia_js_pelaksana_arsitektur' => $model->penyedia_js_pelaksana_arsitektur,
'no_serti_js_pelaksana_arsitektur' => $model->no_serti_js_pelaksana_arsitektur,
'penyedia_js_pengawas_arsitektur' => $model->penyedia_js_pengawas_arsitektur,
'no_serti_js_pengawas_arsitektur' => $model->no_serti_js_pengawas_arsitektur,
'penyedia_js_perencanaan_struktur' => $model->penyedia_js_perencanaan_struktur,
'no_serti_js_perencanaan_struktur' => $model->no_serti_js_perencanaan_struktur,
'penyedia_js_pelaksana_struktur' => $model->penyedia_js_pelaksana_struktur,
'no_serti_js_pelaksana_struktur' => $model->no_serti_js_pelaksana_struktur,
'penyedia_js_pengawas_struktur' => $model->penyedia_js_pengawas_struktur,
'no_serti_js_pengawas_struktur' => $model->no_serti_js_pengawas_struktur,
'penyedia_js_perencanaan_utilitas' => $model->penyedia_js_perencanaan_utilitas,
'no_serti_js_perencanaan_utilitas' => $model->no_serti_js_perencanaan_utilitas,
'penyedia_js_pelaksana_utilitas' => $model->penyedia_js_pelaksana_utilitas,
'no_serti_js_pelaksana_utilitas' => $model->no_serti_js_pelaksana_utilitas,
'penyedia_js_pengawas_utilitas' => $model->penyedia_js_pengawas_utilitas,
'no_serti_js_pengawas_utilitas' => $model->no_serti_js_pengawas_utilitas,

        ];
    }

    public function transformPaginate($model) {

        $data = $model->getCollection()->transform(function($model, $key) {
            return [
               'id' => $model->id,
               'lokasi_kode' => $model->lokasi_kode,
               'thn_periode_keg' => $model->thn_periode_keg,
               'nama_propinsi' => $model->nama_propinsi,
               'nama_kabupatenkota' => $model->nama_kabupatenkota,
               'no_perbub_perwal' => $model->no_perbub_perwal,
'tgl_penetapan_perbub_perwal' => $model->tgl_penetapan_perbub_perwal,
'file_upload_perbub_perwal' => $model->file_upload_perbub_perwal,
'no_surat_krk' => $model->no_surat_krk,
'nama_permohonan_imb' => $model->nama_permohonan_imb,
'nama_pemilik_perorangan_bg_imb' => $model->nama_pemilik_perorangan_bg_imb,
'pemilik_perorangan_bg_imb_id' => $model->pemilik_perorangan_bg_imb_id,
'nama_pemilik_badan_usaha_bg_imb' => $model->nama_pemilik_badan_usaha_bg_imb,
'no_akta_pendirian_badan_usaha_bg_imb' => $model->no_akta_pendirian_badan_usaha_bg_imb,
'nama_institusi_imb' => $model->nama_institusi_imb,
'no_ikmn_pemerintah_imb' => $model->no_ikmn_pemerintah_imb,
'no_hdno_pemerintah_imb' => $model->no_hdno_pemerintah_imb,
'propinsi_pemilik_bg_imb' => $model->propinsi_pemilik_bg_imb,
'kabkota_pemilik_bg_imb' => $model->kabkota_pemilik_bg_imb,
'kec_pemilik_bg_imb' => $model->kec_pemilik_bg_imb,
'kel_pemilik_bg_imb' => $model->kel_pemilik_bg_imb,
'rt_pemilik_bg_imb' => $model->rt_pemilik_bg_imb,
'rw_pemilik_bg_imb' => $model->rw_pemilik_bg_imb,
'alamat_pemilik_bg_imb' => $model->alamat_pemilik_bg_imb,
'telp_pemilik_bg_imb' => $model->telp_pemilik_bg_imb,
'email_pemilik_bg_imb' => $model->email_pemilik_bg_imb,
'nama_pemilik_tanah' => $model->nama_pemilik_tanah,
'no_bukti_kepemilikan' => $model->no_bukti_kepemilikan,
'jenis_bukti_kepemilikan' => $model->jenis_bukti_kepemilikan,
'luas_tanah' => $model->luas_tanah,
'satuan_luas_tanah' => $model->satuan_luas_tanah,
'fungsi_bg' => $model->fungsi_bg,
'jml_lantai_bg' => $model->jml_lantai_bg,
'luas_bg' => $model->luas_bg,
'satuan_luas_bg' => $model->satuan_luas_bg,
'luas_lantai_basement' => $model->luas_lantai_basement,
'satuan_lantai_basement' => $model->satuan_lantai_basement,
'tgl_mulai_konstruksi' => $model->tgl_mulai_konstruksi,
'tgl_selesai_konstruksi' => $model->tgl_selesai_konstruksi,
'nilai_bg_sesuai_rab' => $model->nilai_bg_sesuai_rab,
'lat_bg' => $model->lat_bg,
'long_bg' => $model->long_bg,
'tek_bg_rg_terbuka_hijau_pekarangan' => $model->tek_bg_rg_terbuka_hijau_pekarangan,
'tek_bg_limbah_b3' => $model->tek_bg_limbah_b3,
'tek_bg_memiliki_perangkat_penangkal_kebakaran' => $model->tek_bg_memiliki_perangkat_penangkal_kebakaran,
'tek_jenis_sanitasi' => $model->tek_jenis_sanitasi,
'tek_bg_sumber_air' => $model->tek_bg_sumber_air,
'penyedia_js_perencanaan_arsitektur' => $model->penyedia_js_perencanaan_arsitektur,
'no_serti_js_perencanaan_arsitektur' => $model->no_serti_js_perencanaan_arsitektur,
'penyedia_js_pelaksana_arsitektur' => $model->penyedia_js_pelaksana_arsitektur,
'no_serti_js_pelaksana_arsitektur' => $model->no_serti_js_pelaksana_arsitektur,
'penyedia_js_pengawas_arsitektur' => $model->penyedia_js_pengawas_arsitektur,
'no_serti_js_pengawas_arsitektur' => $model->no_serti_js_pengawas_arsitektur,
'penyedia_js_perencanaan_struktur' => $model->penyedia_js_perencanaan_struktur,
'no_serti_js_perencanaan_struktur' => $model->no_serti_js_perencanaan_struktur,
'penyedia_js_pelaksana_struktur' => $model->penyedia_js_pelaksana_struktur,
'no_serti_js_pelaksana_struktur' => $model->no_serti_js_pelaksana_struktur,
'penyedia_js_pengawas_struktur' => $model->penyedia_js_pengawas_struktur,
'no_serti_js_pengawas_struktur' => $model->no_serti_js_pengawas_struktur,
'penyedia_js_perencanaan_utilitas' => $model->penyedia_js_perencanaan_utilitas,
'no_serti_js_perencanaan_utilitas' => $model->no_serti_js_perencanaan_utilitas,
'penyedia_js_pelaksana_utilitas' => $model->penyedia_js_pelaksana_utilitas,
'no_serti_js_pelaksana_utilitas' => $model->no_serti_js_pelaksana_utilitas,
'penyedia_js_pengawas_utilitas' => $model->penyedia_js_pengawas_utilitas,
'no_serti_js_pengawas_utilitas' => $model->no_serti_js_pengawas_utilitas,

            ];
        });

        $result = [
            'totalRow' => $model->total(),
            'perPage' => $model->count(),
            'currentPage' => $model->currentPage(),
            'lastPage' => $model->lastPage(),
            'data' => $data,
        ];

        return $result;
    }
}
